# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99cd211a62688f3c88faf9667dddeb8de762918959e8ac17f496af7f7dd262fca93284f8ed8dc911b5727fd8b05d7a72f63111a49e6e8dd1237caf4363936b6e

test:
  secret_key_base: 34760be259d534eb89970738baa85ff0a030333898c433b31e20538605f700952c03b0290d4606fa5dcd70f9f33a62a623a12ac2ff1bbc6479b7b5e6626ce58f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
